# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: "katy dynarski -- ecosystem biogeochemist & science writer"
description: >- # this means to ignore newlines until "baseurl:"
  Katy Dynarski's website and blog
baseurl: "" # the subpath of the site
url: "" # the base hostname & protocol for the site
og_image: /assets/img/MoxieFive.jpg
google_analytics: ""

header:
  pages:
    - name: Home
      slug: /
    - name: Blog
    - name: Science
    - name: Writing

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: katy.dynarski@gmail.com
      link: mailto:katy.dynarski@gmail.com

  follow:
    - name: Twitter
      link: http://twitter.com/katydynarski
      username: "@katydynarski"


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
