# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: "katy dynarski -- ecosystem biogeochemist & science writer"
description: >- # this means to ignore newlines until "baseurl:"
  Katy Dynarski's website and blog
baseurl: "" # the subpath of the site
url: "" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: ""

header:
  pages:
    - name: Home
      slug: /
    - name: Science
    - name: Writing
    - name: Blog
    - name: Grant Resources

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: katy@dynarski.net (protonmail)
      link: mailto:katy@dynarski.net

  follow:
    - name: Twitter
      link: http://twitter.com/katydynarski
      username: "@katydynarski"
    - name: Scholar
      link: https://scholar.google.com/citations?user=FKOVyBgAAAAJ&hl=en&authuser=1
    - name: ORCID
      link: https://orcid.org/0000-0001-5101-9666
    - name: RGate
      link: https://www.researchgate.net/profile/Katherine_Dynarski


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
